In [1]:
import pandas as pd
import requests
import csv
import numpy as np
import json
import matplotlib.pyplot as plt
import os
from config1 import g_key
!pip install gmaps
import gmaps

Requirement already satisfied: gmaps in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (0.9.0)
Requirement already satisfied: six in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from gmaps) (1.12.0)
Requirement already satisfied: traitlets>=4.3.0 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from gmaps) (4.3.3)
Requirement already satisfied: ipywidgets>=7.0.0 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from gmaps) (7.5.1)
Requirement already satisfied: ipython>=5.3.0 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from gmaps) (7.8.0)
Requirement already satisfied: geojson>=2.0.0 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from gmaps) (2.5.0)
Requirement already satisfied: decorator in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from traitlets>=4.3.0->gmaps) (4.4.0)
Requirement already satisfied: ipython-genutils in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from traitlets>=4.3.0->gmaps) (0.2.0)
Requirement already satisfied: nbformat>=4.2.0 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.0.0->gmaps) (4.4.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.1)
Requirement already satisfied: ipykernel>=4.5.1 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.0.0->gmaps) (5.1.2)
Requirement already satisfied: pygments in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (2.4.2)
Requirement already satisfied: backcall in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.1.0)
Requirement already satisfied: setuptools>=18.5 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (41.4.0)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (2.0.10)
Requirement already satisfied: pexpect; sys_platform != "win32" in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (4.7.0)
Requirement already satisfied: appnope; sys_platform == "darwin" in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.1.0)
Requirement already satisfied: jedi>=0.10 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.15.1)
Requirement already satisfied: pickleshare in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: jupyter-core in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.5.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.0.2)
Requirement already satisfied: notebook>=4.4.1 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.0.1)
Requirement already satisfied: jupyter-client in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (5.3.3)
Requirement already satisfied: tornado>=4.2 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.0.3)
Requirement already satisfied: wcwidth in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.1.7)
Requirement already satisfied: ptyprocess>=0.5 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=5.3.0->gmaps) (0.6.0)
Requirement already satisfied: parso>=0.5.0 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from jedi>=0.10->ipython>=5.3.0->gmaps) (0.5.1)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.15.4)
Requirement already satisfied: attrs>=17.4.0 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (19.2.0)
Requirement already satisfied: prometheus-client in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.7.1)
Requirement already satisfied: nbconvert in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (5.6.0)
Requirement already satisfied: jinja2 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.10.3)
Requirement already satisfied: terminado>=0.8.1 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.2)
Requirement already satisfied: pyzmq>=17 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (18.1.0)
Requirement already satisfied: Send2Trash in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: python-dateutil>=2.1 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.0)
Requirement already satisfied: defusedxml in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.6.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.4.2)
Requirement already satisfied: entrypoints>=0.2.2 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.3)
Requirement already satisfied: bleach in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (3.1.0)
Requirement already satisfied: testpath in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.4.2)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.1.1)
Requirement already satisfied: webencodings in /Users/NoamanJameel/opt/anaconda3/lib/python3.7/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)

In [5]:
weather_data = pd.read_csv("../WeatherPy/weather_data.csv")
weather_data.head()

,Unnamed: 0,City,Country,Latitude,Longitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (MPH)
0,0,Jamestown,US,42.10,-79.24,1.87,91,1,8.05
1,1,Mirny,RU,62.54,113.96,12.20,92,75,6.71
2,2,Busselton,AU,-33.65,115.33,77.47,35,0,21.30
3,3,Saint-Philippe,RE,-21.36,55.77,76.95,78,100,6.93
4,4,Vaini,TO,-21.20,-175.20,78.80,78,20,9.17

In [6]:
gmaps.configure(api_key=g_key)

In [7]:
locations = weather_data[["Latitude", "Longitude"]]
humidity = weather_data["Humidity (%)"]
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
## Narrow down the DataFrame to find your ideal weather condition

new_weather_data= weather_data.loc[(weather_data["Temperature (F)"] < 80) & (weather_data["Temperature (F)"] > 70) \
                                    & (weather_data["Wind Speed (MPH)"] < 10) \
                                    & (weather_data["Cloudiness (%)"] == 0)].dropna()
new_weather_data
new_weather_data.set_index('City')

,Unnamed: 0,Country,Latitude,Longitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (MPH)
City,,,,,,,,
Minab,35,IR,27.15,57.08,73.40,53,0,6.93
San Patricio,80,MX,19.22,-104.70,76.30,63,0,2.66
Oodweyne,105,SO,9.41,45.06,79.95,28,0,8.14
Esna,107,EG,25.29,32.55,73.40,35,0,4.59
Ormara,123,PK,25.21,64.64,73.44,40,0,4.27
Bahia Honda,153,CU,22.90,-83.16,74.08,81,0,7.99
Puerto Escondido,159,MX,15.85,-97.07,70.75,56,0,5.91
Bonthe,233,SL,7.53,-12.51,79.09,78,0,5.17
Suleja,286,NG,9.18,7.18,78.80,34,0,4.70
Riyadh,294,SA,24.69,46.72,71.60,18,0,4.70
Pochutla,351,MX,15.74,-96.47,72.00,85,0,2.08
Port Blair,352,IN,11.67,92.75,79.38,55,0,9.15
Conakry,385,GN,9.54,-13.68,77.00,73,0,6.02
West Bay,433,KY,19.37,-81.42,77.68,79,0,5.01
Richards Bay,446,ZA,-28.78,32.04,79.43,83,0,9.51
Salto,468,UY,-31.38,-57.97,73.99,95,0,5.01
Samarai,509,PG,-10.62,150.67,79.41,77,0,5.19
Bara,522,NG,10.37,10.73,79.11,8,0,9.17
Concordia,562,AR,-31.39,-58.02,73.99,95,0,5.01
Diu,584,IN,20.71,70.98,75.51,53,0,6.58

In [9]:
## Creating a Dataframe to hold Hotel Data

hotel_data = new_weather_data[["City", "Country", "Latitude", "Longitude"]].copy()
hotel_data["Hotel Name"] = ""
hotel_data

                 City Country  Latitude  Longitude Hotel Name
35              Minab      IR     27.15      57.08
80       San Patricio      MX     19.22    -104.70
105          Oodweyne      SO      9.41      45.06
107              Esna      EG     25.29      32.55
123            Ormara      PK     25.21      64.64
153       Bahia Honda      CU     22.90     -83.16
159  Puerto Escondido      MX     15.85     -97.07
233            Bonthe      SL      7.53     -12.51
286            Suleja      NG      9.18       7.18
294            Riyadh      SA     24.69      46.72
351          Pochutla      MX     15.74     -96.47
352        Port Blair      IN     11.67      92.75
385           Conakry      GN      9.54     -13.68
433          West Bay      KY     19.37     -81.42
446      Richards Bay      ZA    -28.78      32.04
468             Salto      UY    -31.38     -57.97
509           Samarai      PG    -10.62     150.67
522              Bara      NG     10.37      10.73
562         Concordia      AR    -31.39     -58.02
584               Diu      IN     20.71      70.98

In [10]:
## Using Google Places API to find the first hotel for each city located within 5000 meters of your coordinates.

params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}

# Iterate through 
for index, row in hotel_data.iterrows():
    # get lat, lng from df
    lat = row["Latitude"]
    lng = row["Longitude"]
    
    params["location"] = f"{lat},{lng}"
    
    # Use the search term: "Hotel" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
    # convert to json
    name_address = name_address.json()
    
    # Grab the first hotel from the results and store the name
    try:
        hotel_data.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

hotel_data.head()

Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.

             City Country  Latitude  Longitude Hotel Name
35          Minab      IR     27.15      57.08
80   San Patricio      MX     19.22    -104.70
105      Oodweyne      SO      9.41      45.06
107          Esna      EG     25.29      32.55
123        Ormara      PK     25.21      64.64

In [12]:

info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""

hotel_info = [info_box_template.format(**row) for index, row in hotel_data.iterrows()]
locations = hotel_data[["Latitude", "Longitude"]]

In [13]:
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))